config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :skip => [:registrations]
  devise_scope :user do  
    delete '/users/sign_out' => 'devise/sessions#destroy'     
  end
  root to: "home#index"
  #HOME ROUTES
  get 'home/index'
  get 'home/create' => 'home#create'
  post 'home/store' => 'home#store'

    #USERS ROUTES
    get 'users/index'
    get 'users/create' => 'users#create'
    get 'users/search'
    get 'users/update' => 'users#update'
    post 'users/store' => 'users#store'
    post 'users/edit/:id', to: 'users#edit'
    post 'users/delete/:id', to: 'users#delete'
    post 'users/restore/:id', to: 'users#restore'
    #PROYECTOS ROUTES
    get 'proyectos/index'
    get 'proyectos/create' => 'proyectos#create'
    get 'proyectos/search'
    get 'proyectos/show_ended'
    get 'proyectos/update' => 'proyectos#update'
    post 'proyectos/store' => 'proyectos#store'
    post 'proyectos/edit/:id', to: 'proyectos#edit'
    post 'proyectos/edit_lider/:id', to: 'proyectos#edit_lider'
    post 'proyectos/delete/:id', to: 'proyectos#delete'
    #DASHBOARD ROUTES
    get 'dashboard/index'
    get 'dashboard/change'
    post 'dashboard/change-password/:id' => 'dashboard#changePass'
    #ERROR ROUTES
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"

    #RUTAS PARA METODOLOGÍA TSP
    namespace :lanzamiento do
      #LANZAMIENTO::PERSONAL
      get 'personal/index'
      get 'personal/add' => 'personal#add'
      post 'personal/store' => 'personal#store'
      post 'personal/delete/:id', to: 'personal#delete'
      #LANZAMIENTO::METAS
      get 'metas/index'
      get 'metas/create' => 'metas#create'
      get 'metas/update' => 'metas#update'
      post 'metas/store' => 'metas#store'
      post 'metas/edit/:id', to: 'metas#edit'
      post 'metas/delete/:id', to: 'metas#delete'
    end
    namespace :planeacion do
      #PLANEACION::PLANES_DE_CALIDAD
      get 'planes_calidad/index'
      get 'planes_calidad/create' => 'planes_calidad#create'
      get 'planes_calidad/update' => 'planes_calidad#update'
      post 'planes_calidad/store' => 'planes_calidad#store'
      post 'planes_calidad/edit/:id', to: 'planes_calidad#edit'
      post 'planes_calidad/delete/:id', to: 'planes_calidad#delete'
    end
    namespace :estrategia do
      #ESTRATEGIA::CRITERIOS
      get 'criterios/index'
      get 'criterios/create' => 'criterios#create'
      get 'criterios/update' => 'criterios#update'
      post 'criterios/store' => 'criterios#store'
      post 'criterios/edit/:id', to: 'criterios#edit'
      post 'criterios/delete/:id', to: 'criterios#delete'
      #ESTRATEGIA::DISEÑOS
      get 'disenos/index'
      get 'disenos/create' => 'disenos#create'
      get 'disenos/update' => 'disenos#update'
      post 'disenos/store' => 'disenos#store'
      post 'disenos/edit/:id', to: 'disenos#edit'
      post 'disenos/delete/:id', to: 'disenos#delete'
      #ESTRATEGIA::ESTIMACIONES
      get 'estimaciones/index'
      get 'estimaciones/create'
      get 'estimaciones/update'
      post 'estimaciones/store' => 'estimaciones#store'
      post 'estimaciones/edit/:id', to: 'estimaciones#edit'
      post 'estimaciones/delete/:id', to: 'estimaciones#delete'
    end
    namespace :requerimientos do
      #REQUERIMIENTOS::REQUERIMIENTOS
      get 'requerimientos/index'
      get 'requerimientos/create' => 'requerimientos#create'
      get 'requerimientos/update' => 'requerimientos#update'
      post 'requerimientos/store' => 'requerimientos#store'
      post 'requerimientos/edit/:id', to: 'requerimientos#edit'
      post 'requerimientos/delete/:id', to: 'requerimientos#delete'
    end
    namespace :postmortem do
      #POSTMORTEM::RESUMENES
      get 'resumenes/index'
      get 'resumenes/create' => 'resumenes#create'
      get 'resumenes/update' => 'resumenes#update'
      post 'resumenes/store' => 'resumenes#store'
      post 'resumenes/edit/:id', to: 'resumenes#edit'
      post 'resumenes/update_project/:proyecto_id', to: 'resumenes#update_ciclo_proyecto'
      post 'resumenes/end_project/:proyecto_id', to: 'resumenes#end_proyecto'
      post 'resumenes/delete/:id', to: 'resumenes#delete'
    end
    namespace :pruebas do
      #PRUEBAS::PRUEBAS
      get 'pruebas/index'
      get 'pruebas/create'
      get 'pruebas/update'
      post 'pruebas/store' => 'pruebas#store'
      post 'pruebas/edit/:id', to: 'pruebas#edit'
      post 'pruebas/delete/:id', to: 'pruebas#delete'
    end
    namespace :implementacion do
      get 'criterios_calidad/index'
      get 'criterios_calidad/create'
      get 'criterios_calidad/update'
      post 'criterios_calidad/store' => 'criterios_calidad#store'
      post 'criterios_calidad/edit/:id', to: 'criterios_calidad#edit'
      post 'criterios_calidad/delete/:id', to: 'criterios_calidad#delete'
    end
    namespace :diseno do
      #DISENO::TIPOS_ESTANDARES
      get 'tipos_estandares/index'
      get 'tipos_estandares/create'
      get 'tipos_estandares/update'
      post 'tipos_estandares/store' => 'tipos_estandares#store'
      post 'tipos_estandares/edit/:id', to: 'tipos_estandares#edit'
      post 'tipos_estandares/delete/:id', to: 'tipos_estandares#delete'
      #DISENO::ESTANDARES
      get 'estandares/index'
      get 'estandares/create'
      get 'estandares/update'
      post 'estandares/store' => 'estandares#store'
      post 'estandares/edit/:id', to: 'estandares#edit'
      post 'estandares/delete/:id', to: 'estandares#delete'
      #DISENO::PLANES_PRUEBAS
      get 'planes_pruebas/index'
      get 'planes_pruebas/create'
      get 'planes_pruebas/update'
      post 'planes_pruebas/store' => 'planes_pruebas#store'
      post 'planes_pruebas/edit/:id', to: 'planes_pruebas#edit'
      post 'planes_pruebas/delete/:id', to: 'planes_pruebas#delete'
      #DISENO::ESTRUCUTURAS
      get 'estructuras/index'
      get 'estructuras/create'
      get 'estructuras/update'
      post 'estructuras/store' => 'estructuras#store'
      post 'estructuras/edit/:id', to: 'estructuras#edit'
      post 'estructuras/delete/:id', to: 'estructuras#delete'
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/diseno.rb
module Diseno
  def self.table_name_prefix
    'diseno_'
  end
end

app/models/diseno/estandar.rb
class Diseno::Estandar < ApplicationRecord
    belongs_to :colaborador, class_name: 'Colaborador'
    belongs_to :tipo_estandar, class_name: 'Diseno::TipoEstandar'
end

app/models/diseno/estructura.rb
class Diseno::Estructura < ApplicationRecord
    belongs_to :colaborador, class_name: 'Colaborador'
end

app/controllers/diseno/estandares_controller.rb
class Diseno::EstandaresController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource

  layout 'application_dashboard'

  def index
    begin
      @proyecto = Proyecto.find(params[:proyecto_id])
      @colaboradors = nil
      if current_user.role_id == 2
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id])
      else
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id)
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "No se ha seleccionado el proyecto"
      redirect_to dashboard_index_path
    end
  end

  def create
    @diseno = Diseno::Estandar.new
    @tipos_estandares = nil
    if Diseno::TipoEstandar.where(proyecto_id: params[:proyecto_id]) == nil
      flash[:danger] = "No tiene registrado ningún tipo de estándar."
      redirect_to diseno_estandares_index_path(:proyecto_id => params[:proyecto_id])
    else
      @tipo_estandares = Diseno::TipoEstandar.where(proyecto_id: params[:proyecto_id])
    end
  end

  def store
    #Definición e inicialización de nueva Diseno
    @colaborador = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id).first
    @estandar = Diseno::Estandar.new(parametros)
    #obteniendo el ciclo del proyecto
    @estandar.diseno_tipo_estandar_id = Diseno::TipoEstandar.find(params[:diseno_tipo_estandar_id]);
    @estandar.ciclo = Proyecto.find(params[:proyecto_id]).ciclo_actual
    @estandar.colaborador_id = @colaborador.id
    if(@estandar.save)
      #Impresión del proceso satisfactorio
      flash[:success] = "Estándar creado Correctamente"
    else
      #Impresión del proceso satisfactorio
      flash[:danger] = "No se pudo crear el estándar"
    end
    redirect_to diseno_estandares_index_path(:proyecto_id => params[:proyecto_id])
  end

  def edit
    @estandar = Diseno::Estandar.find(params[:id])
    @estandar = Diseno::Estandar.where(id: @estandar).first
    if @estandar.update(parametros)
      #Impresión del proceso satisfactorio
      flash[:success] = "Estándar Actualizado Correctamente"
    else
      #Impresión del proceso satisfactorio
      flash[:danger] = "Estándar no se pudo actualizar"
    end
    redirect_to diseno_estandares_index_path(:proyecto_id => params[:proyecto_id])
  end

  def update
    begin
      @estandar = Diseno::Estandar.find(params[:id])
      @estandar = Diseno::Estandar.where(id: @estandar)
    rescue ActiveRecord::RecordNotFound => e
      @estandar = nil
      flash[:danger] = "No se encontró el estándar"
      redirect_to diseno_estandares_index_path(:proyecto_id => params[:proyecto_id])
    end
  end

  def delete
    @estandar = Diseno::Estandar.find(params[:id])
    Diseno::Estandares.where(id: @estandar).destroy_all
    flash[:success] = "Estándar de pruebas Eliminado"
    redirect_to diseno_estandares_index_path(:proyecto_id => params[:proyecto_id])
  end

  private
  def parametros
    params.permit(:nombre, :descripcion, :ciclo, :diseno_tipo_estandar_id)
  end
end

app/controllers/diseno/estructuras_controller.rb
class Diseno::EstructurasController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  layout 'application_dashboard'

  def index
    begin
      @proyecto = Proyecto.find(params[:proyecto_id])
      @colaboradors = nil
      if current_user.role_id == 2
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id])
      else
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id)
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "No se ha seleccionado el proyecto"
      redirect_to dashboard_index_path
    end
  end

  def create
    @diseno = Diseno::Estructura.new
  end

  def store
    #Definición e inicialización de nueva Diseno
    @colaborador = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id).first
    @estructura = Diseno::Estructura.new(parametros)
    #obteniendo el ciclo del proyecto
    @estructura.ciclo = Proyecto.find(params[:proyecto_id]).ciclo_actual
    @estructura.colaborador_id = @colaborador.id
    if(@estructura.save)
      #Impresión del proceso satisfactorio
      flash[:success] = "Estructura Creada Correctamente"
    else
      #Impresión del proceso satisfactorio
      flash[:danger] = "No se pudo crear la estructura"
    end
    redirect_to diseno_estructuras_index_path(:proyecto_id => params[:proyecto_id])
  end

  def edit
    @estructura = Diseno::Estructura.find(params[:id])
    @estructura = Diseno::Estructura.where(id: @estructura).first
    if @estructura.update(parametros)
      #Impresión del proceso satisfactorio
      flash[:success] = "Estructura Actualizado Correctamente"
    else
      #Impresión del proceso satisfactorio
      flash[:danger] = "La estructura no se pudo actualizar"
    end
    redirect_to diseno_estructuras_index_path(:proyecto_id => params[:proyecto_id])
  end

  def update
    begin
      @estructura = Diseno::Estructura.find(params[:id])
      @estructura = Diseno::Estructura.where(id: @estructura)
    rescue ActiveRecord::RecordNotFound => e
      @Diseno = nil
      flash[:danger] = "Estrucutra No Encontrada"
      redirect_to diseno_estructuras_index_path(:proyecto_id => params[:proyecto_id])
    end
  end

  def delete
    @estructura = Diseno::Estructura.find(params[:id])
    Diseno::Estructura.where(id: @estructura).destroy_all
    flash[:success] = "Estructura Eliminada"
    redirect_to diseno_estructuras_index_path(:proyecto_id => params[:proyecto_id])
  end

  private
  def parametros
    params.permit( :nombre, :descripcion, :ciclo)
  end
end

app/controllers/diseno/planes_pruebas_controller.rb
class Diseno::PlanesPruebasController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource :class => Diseno::PlanPruebas

  layout 'application_dashboard'

  def index
    begin
      @proyecto = Proyecto.find(params[:proyecto_id])
      @colaboradors = nil
      if current_user.role_id == 2
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id])
      else
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id)
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "No se ha seleccionado el proyecto"
      redirect_to dashboard_index_path
    end
  end

  def create
    @planPruebas = Diseno::PlanPruebas.new
  end

  def store
    #Definición e inicialización de nueva Diseno
    @colaborador = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id).first
    @planPruebas = Diseno::PlanPruebas.new(parametros)
    #obteniendo el ciclo del proyecto
    @planPruebas.ciclo = Proyecto.find(params[:proyecto_id]).ciclo_actual
    @planPruebas.colaborador_id = @colaborador.id
    if(@planPruebas.save)
      #Impresión del proceso satisfactorio
      flash[:success] = "Plan de pruebas Creado Correctamente"
    else
      #Impresión del proceso satisfactorio
      flash[:danger] = "No se pudo crear la Plan de pruebas"
    end
    redirect_to diseno_planes_pruebas_index_path(:proyecto_id => params[:proyecto_id])
  end

  def edit
    @planPruebas = Diseno::PlanPruebas.find(params[:id])
    @planPruebas = Diseno::PlanPruebas.where(id: @planPruebas).first
    if @planPruebas.update(parametros)
      #Impresión del proceso satisfactorio
      flash[:success] = "Plan de Pruebas Actualizado Correctamente"
    else
      #Impresión del proceso satisfactorio
      flash[:danger] = "Plan de pruebas actualiza la estimación"
    end
      redirect_to diseno_planes_pruebas_index_path(:proyecto_id => params[:proyecto_id])
  end

  def update
    begin
      @planPruebas = Diseno::PlanPruebas.find(params[:id])
      @planPruebas = Diseno::PlanPruebas.where(id: @planPruebas)
    rescue ActiveRecord::RecordNotFound => e
      @planPruebas = nil
      flash[:danger] = "Plan de pruebas no encontrado"
      redirect_to diseno_planes_pruebas_index_path(:proyecto_id => params[:proyecto_id])
    end
  end

  def delete
    @planPruebas = Diseno::PlanPruebas.find(params[:id])
    Diseno::PlanPruebas.where(id: @planPruebas).destroy_all
    flash[:success] = "Plan de Pruebas Eliminado"
    redirect_to diseno_planes_pruebas_index_path(:proyecto_id => params[:proyecto_id])
  end

  private
  def parametros
    params.permit( :nombre, :descripcion, :ciclo)
  end
end

app/controllers/diseno/tipos_estandares_controller.rb
class Diseno::TiposEstandaresController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource

  layout 'application_dashboard'

  def index
    begin
      @proyecto = Proyecto.find(params[:proyecto_id])
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "No se ha seleccionado el proyecto"
      redirect_to dashboard_index_path
    end
  end

  def create
    @tipoEstandar = Diseno::TipoEstandar.new
  end

  def store
    #Definición e inicialización de nueva Diseno
    @tipoEstandar = Diseno::TipoEstandar.new(parametros)
    @tipoEstandar.proyecto_id = params[:proyecto_id]
    if(@tipoEstandar.save)
      #Impresión del proceso satisfactorio
      flash[:success] = "Tipo de Estándar Creado Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "No se pudo crear el Tipo de Estándar"
    end
    redirect_to diseno_tipos_estandares_index_path(:proyecto_id => params[:proyecto_id])
  end

  def edit
    @tipoEstandar = Diseno::TipoEstandar.find(params[:id])
    @tipoEstandar = Diseno::TipoEstandar.where(id: @tipoEstandar).first
    if @tipoEstandar.update(parametros)
      #Impresión del proceso satisfactorio
      flash[:success] = "Tipo de Estándar Actualizado Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "El Estándar No Se Actualizó"
    end
      redirect_to diseno_tipos_estandares_index_path(:proyecto_id => params[:proyecto_id])
  end

  def update
    begin
      @tipoEstandar = Diseno::TipoEstandar.find(params[:id])
      @tipoEstandar = Diseno::TipoEstandar.where(id: @tipoEstandar)
    rescue ActiveRecord::RecordNotFound => e
      @tipoEstandar = nil
      flash[:danger] = "No Se Encontró El Estándar"
      redirect_to diseno_tipos_estandares_index_path(:proyecto_id => params[:proyecto_id])
    end
  end

  def delete
    @tipoEstandar = Diseno::TipoEstandar.find(params[:id])
    Diseno::TipoEstandar.where(id: @tipoEstandar).destroy_all
    flash[:success] = "Estándar Eliminado"
    redirect_to diseno_tipos_estandares_index_path(:proyecto_id => params[:proyecto_id])
  end

  private
  def parametros
    params.permit( :nombre, :descripcion)
  end
end

app/helpers/diseno/estandares_helper.rb
module Diseno::EstandaresHelper
end

app/helpers/diseno/estructuras_helper.rb
module Diseno::EstructurasHelper
end

app/helpers/diseno/planes_pruebas_helper.rb
module Diseno::PlanesPruebasHelper
end

app/helpers/diseno/tipos_estandares_helper.rb
module Diseno::TiposEstandaresHelper
end

app/helpers/estrategia/disenos_helper.rb
module Estrategia::DisenosHelper
end

app/views/diseno/planes_pruebas/create.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=Proyecto.find(params[:proyecto_id]).nombre%></h2>
    <br>
    <div class="container">
        <div class="row justify-content-md-center align-items-center">
            <div class="col-md-10 align-item-center">
            <div class="card text-center">
                <div class="card-header">
                    <h3>Diseño  : :  Planes de Pruebas | Crear Plan de Pruebas</h3>
                </div>
                <div class="card-body bg-aqua justify-content-center">
                    <form method="POST" action="store" accept-charset="UTF-8" role="form" id="crearplanpruebas" name="crearplanpruebas" enctype="multipart/form-data"> 
                        <!-- Protección CSRF -->
                        <%= token_tag nil %>
                        <div class="row">
                            <div class="col-md-2">
                                <input type="hidden" id="proyecto_id" name="proyecto_id" value="<%=params[:proyecto_id]%>">
                                <label class="text-white">Nombre</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="text" class="form-control" placeholder="Nombre" id="nombre" name="nombre" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Descripción</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Descripción" id="descripcion" name="descripcion" required></textarea>
                            </div>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <button type="submit" class="btn btn-light">Guardar</button>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <%= link_to 'Cancelar', url_for(:back), class: "btn btn-warning" %>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>

app/views/diseno/planes_pruebas/index.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=@proyecto.nombre%></h2>
    <br>
    <div class="card bg-aqua">
        <div class="row card-header text-white">
            <h3 class="col-md-10">Diseño  : :  Planes Pruebas</h3>
            <%= link_to 'Agregar Plan de Pruebas', diseno_planes_pruebas_create_path(:proyecto_id => @proyecto.id), class: "btn btn-light col-md-2 float-right" %>
        </div>
        <table class="table table-hover table-sm table-dark card-body">
            <thead>
                <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col" style="width: 10%">Acciones</th>
                </tr>
            </thead>
            <tbody>
            <% @colaboradors.each do |colab|%>
                <% colab.diseno_planes_pruebas.each do |plan|%>
                    <tr>
                    <td><%=plan.nombre%></td>
                    <td><%=plan.descripcion%></td>
                    <td>
                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-6 px-0">
                                <div class="d-inline-flex">
                                    <a href="/diseno/planes_pruebas/update?id=<%= plan.id %>&proyecto_id=<%=@proyecto.id%>" title="Editar">
                                        <%= image_tag("edit.png", :alt=>"Editar", :width => '30%', :style => " filter: invert(100%)" )%>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6 px-0">
                                <form method="POST" action="/diseno/planes_pruebas/delete/<%=plan.id%>&proyecto_id=<%=@proyecto.id%>" accept-charset="UTF-8" class="form-horizontal" role="form">
                                <!-- Protección CSRF -->
                                <%= token_tag nil %>
                                <div class="d-inline-flex">
                                    <input type="submit" class="btn-delete" title="Eliminar" data-confirm="¿Desea eliminar el plan de pruebas <%=plan.nombre%>?" data-title="Eliminar Plan" data-commit="Eliminar" data-cancel="Cancelar">
                                </div>
                                </form>
                            </div>
                        </div>
                    </td>
                    </tr>
                <% end %>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/diseno/planes_pruebas/update.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=Proyecto.find(params[:proyecto_id]).nombre%></h2>
    <br>
    <div class="container">
        <div class="row justify-content-md-center align-items-center">
            <div class="col-md-10 align-item-center">
            <div class="card text-center">
                <div class="card-header">
                    <h3>Diseño  : :  Planes de Pruebas | Actualizar Plan de Pruebas</h3>
                </div>
                <div class="card-body bg-aqua justify-content-center">
                <% @planPruebas.each do |plan| %>
                    <form method="POST" action="store" accept-charset="UTF-8" role="form" id="actualizarplanpruebas" name="actualizarplanpruebas" enctype="multipart/form-data"> 
                        <!-- Protección CSRF -->
                        <%= token_tag nil %>
                        <div class="row">
                            <div class="col-md-2">
                                <input type="hidden" id="proyecto_id" name="proyecto_id" value="<%=params[:proyecto_id]%>">
                                <label class="text-white">Nombre</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="text" class="form-control" placeholder="Nombre" id="nombre" name="nombre" required value="<%=plan.nombre%>">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Descripción</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Descripción" id="descripcion" name="descripcion" required><%=plan.descripcion%></textarea>
                            </div>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <button type="submit" class="btn btn-light">Guardar</button>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <%= link_to 'Cancelar', url_for(:back), class: "btn btn-warning" %>
                        </div>
                    </form>
                    </div>
                    <%end%>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>