config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :skip => [:registrations]
  devise_scope :user do  
    delete '/users/sign_out' => 'devise/sessions#destroy'     
  end
  root to: "home#index"
  #HOME ROUTES
  get 'home/index'
  get 'home/create' => 'home#create'
  post 'home/store' => 'home#store'

    #USERS ROUTES
    get 'users/index'
    get 'users/create' => 'users#create'
    get 'users/search'
    get 'users/update' => 'users#update'
    post 'users/store' => 'users#store'
    post 'users/edit/:id', to: 'users#edit'
    post 'users/delete/:id', to: 'users#delete'
    post 'users/restore/:id', to: 'users#restore'
    #PROYECTOS ROUTES
    get 'proyectos/index'
    get 'proyectos/create' => 'proyectos#create'
    get 'proyectos/search'
    get 'proyectos/show_ended'
    get 'proyectos/update' => 'proyectos#update'
    post 'proyectos/store' => 'proyectos#store'
    post 'proyectos/edit/:id', to: 'proyectos#edit'
    post 'proyectos/edit_lider/:id', to: 'proyectos#edit_lider'
    post 'proyectos/delete/:id', to: 'proyectos#delete'
    #DASHBOARD ROUTES
    get 'dashboard/index'
    get 'dashboard/change'
    post 'dashboard/change-password/:id' => 'dashboard#changePass'
    #ERROR ROUTES
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"

    #RUTAS PARA METODOLOGÍA TSP
    namespace :lanzamiento do
      #LANZAMIENTO::PERSONAL
      get 'personal/index'
      get 'personal/add' => 'personal#add'
      post 'personal/store' => 'personal#store'
      post 'personal/delete/:id', to: 'personal#delete'
      #LANZAMIENTO::METAS
      get 'metas/index'
      get 'metas/create' => 'metas#create'
      get 'metas/update' => 'metas#update'
      post 'metas/store' => 'metas#store'
      post 'metas/edit/:id', to: 'metas#edit'
      post 'metas/delete/:id', to: 'metas#delete'
    end
    namespace :planeacion do
      #PLANEACION::PLANES_DE_CALIDAD
      get 'planes_calidad/index'
      get 'planes_calidad/create' => 'planes_calidad#create'
      get 'planes_calidad/update' => 'planes_calidad#update'
      post 'planes_calidad/store' => 'planes_calidad#store'
      post 'planes_calidad/edit/:id', to: 'planes_calidad#edit'
      post 'planes_calidad/delete/:id', to: 'planes_calidad#delete'
    end
    namespace :estrategia do
      #ESTRATEGIA::CRITERIOS
      get 'criterios/index'
      get 'criterios/create' => 'criterios#create'
      get 'criterios/update' => 'criterios#update'
      post 'criterios/store' => 'criterios#store'
      post 'criterios/edit/:id', to: 'criterios#edit'
      post 'criterios/delete/:id', to: 'criterios#delete'
      #ESTRATEGIA::DISEÑOS
      get 'disenos/index'
      get 'disenos/create' => 'disenos#create'
      get 'disenos/update' => 'disenos#update'
      post 'disenos/store' => 'disenos#store'
      post 'disenos/edit/:id', to: 'disenos#edit'
      post 'disenos/delete/:id', to: 'disenos#delete'
      #ESTRATEGIA::ESTIMACIONES
      get 'estimaciones/index'
      get 'estimaciones/create'
      get 'estimaciones/update'
      post 'estimaciones/store' => 'estimaciones#store'
      post 'estimaciones/edit/:id', to: 'estimaciones#edit'
      post 'estimaciones/delete/:id', to: 'estimaciones#delete'
    end
    namespace :requerimientos do
      #REQUERIMIENTOS::REQUERIMIENTOS
      get 'requerimientos/index'
      get 'requerimientos/create' => 'requerimientos#create'
      get 'requerimientos/update' => 'requerimientos#update'
      post 'requerimientos/store' => 'requerimientos#store'
      post 'requerimientos/edit/:id', to: 'requerimientos#edit'
      post 'requerimientos/delete/:id', to: 'requerimientos#delete'
    end
    namespace :postmortem do
      #POSTMORTEM::RESUMENES
      get 'resumenes/index'
      get 'resumenes/create' => 'resumenes#create'
      get 'resumenes/update' => 'resumenes#update'
      post 'resumenes/store' => 'resumenes#store'
      post 'resumenes/edit/:id', to: 'resumenes#edit'
      post 'resumenes/update_project/:proyecto_id', to: 'resumenes#update_ciclo_proyecto'
      post 'resumenes/end_project/:proyecto_id', to: 'resumenes#end_proyecto'
      post 'resumenes/delete/:id', to: 'resumenes#delete'
    end
    namespace :pruebas do
      #PRUEBAS::PRUEBAS
      get 'pruebas/index'
      get 'pruebas/create'
      get 'pruebas/update'
      post 'pruebas/store' => 'pruebas#store'
      post 'pruebas/edit/:id', to: 'pruebas#edit'
      post 'pruebas/delete/:id', to: 'pruebas#delete'
    end
    namespace :implementacion do
      get 'criterios_calidad/index'
      get 'criterios_calidad/create'
      get 'criterios_calidad/update'
      post 'criterios_calidad/store' => 'criterios_calidad#store'
      post 'criterios_calidad/edit/:id', to: 'criterios_calidad#edit'
      post 'criterios_calidad/delete/:id', to: 'criterios_calidad#delete'
    end
    namespace :diseno do
      #DISENO::TIPOS_ESTANDARES
      get 'tipos_estandares/index'
      get 'tipos_estandares/create'
      get 'tipos_estandares/update'
      post 'tipos_estandares/store' => 'tipos_estandares#store'
      post 'tipos_estandares/edit/:id', to: 'tipos_estandares#edit'
      post 'tipos_estandares/delete/:id', to: 'tipos_estandares#delete'
      #DISENO::ESTANDARES
      get 'estandares/index'
      get 'estandares/create'
      get 'estandares/update'
      post 'estandares/store' => 'estandares#store'
      post 'estandares/edit/:id', to: 'estandares#edit'
      post 'estandares/delete/:id', to: 'estandares#delete'
      #DISENO::PLANES_PRUEBAS
      get 'planes_pruebas/index'
      get 'planes_pruebas/create'
      get 'planes_pruebas/update'
      post 'planes_pruebas/store' => 'planes_pruebas#store'
      post 'planes_pruebas/edit/:id', to: 'planes_pruebas#edit'
      post 'planes_pruebas/delete/:id', to: 'planes_pruebas#delete'
      #DISENO::ESTRUCUTURAS
      get 'estructuras/index'
      get 'estructuras/create'
      get 'estructuras/update'
      post 'estructuras/store' => 'estructuras#store'
      post 'estructuras/edit/:id', to: 'estructuras#edit'
      post 'estructuras/delete/:id', to: 'estructuras#delete'
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/estrategia.rb
module Estrategia
  def self.table_name_prefix
    'estrategia_'
  end
end

app/models/estrategia/criterio.rb
class Estrategia::Criterio < ApplicationRecord
    belongs_to :colaborador, class_name: 'Colaborador'
end

app/models/estrategia/diseno.rb
class Estrategia::Diseno < ApplicationRecord
    belongs_to :colaborador, class_name: 'Colaborador'
end

app/models/estrategia/estimacion.rb
class Estrategia::Estimacion < ApplicationRecord
    belongs_to :colaborador, class_name: 'Colaborador'
end

app/controllers/estrategia/criterios_controller.rb
class Estrategia::CriteriosController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource

  layout 'application_dashboard'

  def index
    begin
      @proyecto = Proyecto.find(params[:proyecto_id])
      @colaboradors = nil
      if current_user.role_id == 2
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id])
      else
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id)
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "No se ha seleccionado el proyecto"
      redirect_to dashboard_index_path
    end
  end

  def create
    @criterio = Estrategia::Criterio.new
  end

  def store
    #Definición e inicialización de nueva Criterio
    @colaborador = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id).first
    @criterio = Estrategia::Criterio.new(parametros)
    #obteniendo el ciclo del proyecto
    @criterio.ciclo = Proyecto.find(params[:proyecto_id]).ciclo_actual
    @criterio.colaborador_id = @colaborador.id
    if(@criterio.save)
      #Impresión del proceso satisfactorio
      flash[:success] = "Criterio Creado Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "No se pudo crear el Criterio"
    end
      redirect_to estrategia_criterios_index_path(:proyecto_id => params[:proyecto_id])
  end

  def edit
    @criterio = Estrategia::Criterio.find(params[:id])
    @criterio = Estrategia::Criterio.where(id: @criterio).first
    if @criterio.update(parametros)
      #Impresión del proceso satisfactorio
      flash[:success] = "Criterio Actualizado Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "No se pudo actualizar el Criterio"
    end
      redirect_to estrategia_criterios_index_path(:proyecto_id => params[:proyecto_id])
  end

  def update
    begin
      @criterio = Estrategia::Criterio.find(params[:id])
      @criterio = Estrategia::Criterio.where(id: @criterio)
    rescue ActiveRecord::RecordNotFound => e
      @criterio = nil
      flash[:danger] = "Criterio No Registrado"
      redirect_to estrategia_criterios_index_path(:proyecto_id => params[:proyecto_id])
    end
  end

  def delete
    @criterio = Estrategia::Criterio.find(params[:id])
    Estrategia::Criterio.where(id: @criterio).destroy_all
    flash[:success] = "Criterio Eliminado"
    redirect_to estrategia_criterios_index_path(:proyecto_id => params[:proyecto_id])
  end

  private
  def parametros
    params.permit(:descripcion, :ciclo)
  end
end

app/controllers/estrategia/disenos_controller.rb
class Estrategia::DisenosController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource

  layout 'application_dashboard'

  def index
    begin
      @proyecto = Proyecto.find(params[:proyecto_id])
      @colaboradors = nil
      if current_user.role_id == 2
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id])
      else
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id)
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "No se ha seleccionado el proyecto"
      redirect_to dashboard_index_path
    end
  end

  def create
    @diseno = Estrategia::Diseno.new
  end

  def store
    #Definición e inicialización de nueva Diseno
    @colaborador = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id).first
    @diseno = Estrategia::Diseno.new(parametros)
    #obteniendo el ciclo del proyecto
    @diseno.ciclo = Proyecto.find(params[:proyecto_id]).ciclo_actual
    @diseno.colaborador_id = @colaborador.id
    if(@diseno.save)
      #Impresión del proceso satisfactorio
      flash[:success] = "Diseño Creado Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "No se pudo crear el Diseño"
    end
      redirect_to estrategia_disenos_index_path(:proyecto_id => params[:proyecto_id])
  end

  def edit
    @diseno = Estrategia::Diseno.find(params[:id])
    @diseno = Estrategia::Diseno.where(id: @diseno).first
    if @diseno.update(parametros)
      #Impresión del proceso satisfactorio
      flash[:success] = "Diseño Actualizado Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "No se pudo actualizar el Diseño"
    end
      redirect_to estrategia_disenos_index_path(:proyecto_id => params[:proyecto_id])
  end

  def update
    begin
      @diseno = Estrategia::Diseno.find(params[:id])
      @diseno = Estrategia::Diseno.where(id: @diseno)
    rescue ActiveRecord::RecordNotFound => e
      @diseno = nil
      flash[:danger] = "Diseño No Registrado"
      redirect_to estrategia_disenos_index_path(:proyecto_id => params[:proyecto_id])
    end
  end

  def delete
    @diseno = Estrategia::Diseno.find(params[:id])
    Estrategia::Diseno.where(id: @diseno).destroy_all
    flash[:success] = "Diseño Eliminado"
    redirect_to estrategia_disenos_index_path(:proyecto_id => params[:proyecto_id])
  end

  private
  def parametros
    params.permit(:descripcion_producto, :tamano, :ciclo)
  end
end

app/controllers/estrategia/estimaciones_controller.rb
class Estrategia::EstimacionesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  layout 'application_dashboard'

  def index
    begin
      @proyecto = Proyecto.find(params[:proyecto_id])
      @colaboradors = nil
      if current_user.role_id == 2
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id])
      else
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id)
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "No se ha seleccionado el proyecto"
      redirect_to dashboard_index_path
    end
  end

  def create
    @estimacion = Estrategia::Estimacion.new
  end

  def store
    #Definición e inicialización de nueva Estimacion
    @colaborador = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id).first
    @estimacion = Estrategia::Estimacion.new(parametros)
    #obteniendo el ciclo del proyecto
    @estimacion.ciclo = Proyecto.find(params[:proyecto_id]).ciclo_actual
    @estimacion.colaborador_id = @colaborador.id
    if(@estimacion.save)
      #Impresión del proceso satisfactorio
      flash[:success] = "Estimación Creada Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "No se pudo crear la Estimación"
    end
      redirect_to estrategia_estimaciones_index_path(:proyecto_id => params[:proyecto_id])
  end

  def edit
    @estimacion = Estrategia::Estimacion.find(params[:id])
    @estimacion = Estrategia::Estimacion.where(id: @estimacion).first
    if @estimacion.update(parametros)
      #Impresión del proceso satisfactorio
      flash[:success] = "Estimación Actualizada Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "No se pudo actualizar la estimación"
    end
      redirect_to estrategia_estimaciones_index_path(:proyecto_id => params[:proyecto_id])
  end

  def update
    begin
      @estimacion = Estrategia::Estimacion.find(params[:id])
      @estimacion = Estrategia::Estimacion.where(id: @estimacion)
    rescue ActiveRecord::RecordNotFound => e
      @estimacion = nil
      flash[:danger] = "Estimación No Registrada"
      redirect_to estrategia_estimaciones_index_path(:proyecto_id => params[:proyecto_id])
    end
  end

  def delete
    @estimacion = Estrategia::Estimacion.find(params[:id])
    Estrategia::Estimacion.where(id: @estimacion).destroy_all
    flash[:success] = "Estimación Eliminada"
    redirect_to estrategia_estimaciones_index_path(:proyecto_id => params[:proyecto_id])
  end

  private
  def parametros
    params.permit(:funcion, :descripcion, :tamano, :tiempo, :ciclo)
  end
end

app/helpers/estrategia/criterios_helper.rb
module Estrategia::CriteriosHelper
end

app/helpers/estrategia/disenos_helper.rb
module Estrategia::DisenosHelper
end

app/helpers/estrategia/estimaciones_helper.rb
module Estrategia::EstimacionesHelper
end

app/views/estrategia/estimaciones/create.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=Proyecto.find(params[:proyecto_id]).nombre%></h2>
    <br>
    <div class="container">
        <div class="row justify-content-md-center align-items-center">
            <div class="col-md-10 align-item-center">
            <div class="card text-center">
                <div class="card-header">
                    <h3>Estrategia  : :  Estimaciones | Crear Estimación</h3>
                </div>
                <div class="card-body bg-aqua justify-content-center">
                    <form method="POST" action="store" accept-charset="UTF-8" role="form" id="crearestimacion" name="crearestimacion" enctype="multipart/form-data"> 
                        <!-- Protección CSRF -->
                        <%= token_tag nil %>
                        <div class="row">
                            <div class="col-md-2">
                            <input type="hidden" id="proyecto_id" name="proyecto_id" value="<%=params[:proyecto_id]%>">
                                <label class="text-white">Nombre de Función</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Nombre de Función" id="funcion" name="funcion" required></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Descripción</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Descripción" id="descripcion" name="descripcion" required></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Tamaño (LOC)</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="number" class="form-control" placeholder="Tamaño (LOC)" id="tamano" name="tamano" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Tiempo (Hrs)</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="number" class="form-control" placeholder="Tiempo en Horas" id="tiempo" name="tiempo" required>
                            </div>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <button type="submit" class="btn btn-light">Guardar</button>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <%= link_to 'Cancelar', url_for(:back), class: "btn btn-warning" %>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>

app/views/estrategia/estimaciones/index.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=@proyecto.nombre%></h2>
    <br>
    <div class="card bg-aqua">
        <div class="row card-header text-white">
            <h3 class="col-md-10">Estrategia  : :  Estimaciones</h3>
            <%= link_to 'Agregar Estimación', estrategia_estimaciones_create_path(:proyecto_id => @proyecto.id), class: "btn btn-light col-md-2 float-right" %>
        </div>
        <table class="table table-hover table-sm table-dark card-body">
            <thead>
                <tr>
                <th scope="col">Función</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Tamaño(LOC)</th>
                <th scope="col">Tiempo(Hrs)</th>
                <th scope="col" style="width: 10%">Acciones</th>
                </tr>
            </thead>
            <tbody>
            <% @colaboradors.each do |colab|%>
                <% colab.estrategia_estimaciones.each do |estimacion|%>
                    <tr>
                    <td><%=estimacion.funcion%></td>
                    <td><%=estimacion.descripcion%></td>
                    <td><%=estimacion.tamano%></td>
                    <td><%=estimacion.tiempo%></td>
                    <td>
                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-6 px-0">
                                <div class="d-inline-flex">
                                    <a href="/estrategia/estimaciones/update?id=<%= estimacion.id %>&proyecto_id=<%=@proyecto.id%>" title="Editar">
                                        <%= image_tag("edit.png", :alt=>"Editar", :width => '30%', :style => " filter: invert(100%)" )%>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6 px-0">
                                <form method="POST" action="/estrategia/estimaciones/delete/<%=estimacion.id%>&proyecto_id=<%=@proyecto.id%>" accept-charset="UTF-8" class="form-horizontal" role="form">
                                <!-- Protección CSRF -->
                                <%= token_tag nil %>
                                <div class="d-inline-flex">
                                    <input type="submit" class="btn-delete" title="Eliminar" data-confirm="¿Desea eliminar la estimación <%=estimacion.funcion%>?" data-title="Eliminar Estimación" data-commit="Eliminar" data-cancel="Cancelar">
                                </div>
                                </form>
                            </div>
                        </div>
                    </td>
                    </tr>
                <% end %>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/estrategia/estimaciones/update.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=Proyecto.find(params[:proyecto_id]).nombre%></h2>
    <br>
    <div class="container">
        <div class="row justify-content-md-center align-items-center">
            <div class="col-md-10 align-item-center">
            <div class="card text-center">
                <div class="card-header">
                    <h3>Estrategia  : :  Estimaciones | Actualizar Estimación</h3>
                </div>
                <div class="card-body bg-aqua justify-content-center">
                <% @estimacion.each do |estimacion| %>
                    <form method="POST" action="store" accept-charset="UTF-8" role="form" id="actualizarestimacion" name="actualizarestimacion" enctype="multipart/form-data"> 
                        <!-- Protección CSRF -->
                        <%= token_tag nil %>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Nombre de Función</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Nombre de Función" id="funcion" name="funcion" required><%=estimacion.funcion%></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Descripción</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Descripción" id="descripcion" name="descripcion" required><%=estimacion.descripcion%></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Tamaño (LOC)</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="number" class="form-control" placeholder="Tamaño (LOC)" id="tamano" name="tamano" required value="<%=estimacion.tamano%>">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Tiempo (Hrs)</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="number" class="form-control" placeholder="Tiempo en Horas" id="tiempo" name="tiempo" required value="<%=estimacion.tiempo%>">
                            </div>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <button type="submit" class="btn btn-light">Guardar</button>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <%= link_to 'Cancelar', url_for(:back), class: "btn btn-warning" %>
                        </div>
                    </form>
                    </div>
                    <%end%>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>