config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :skip => [:registrations]
  devise_scope :user do  
    delete '/users/sign_out' => 'devise/sessions#destroy'     
  end
  root to: "home#index"
  #HOME ROUTES
  get 'home/index'
  get 'home/create' => 'home#create'
  post 'home/store' => 'home#store'

    #USERS ROUTES
    get 'users/index'
    get 'users/create' => 'users#create'
    get 'users/search'
    get 'users/update' => 'users#update'
    post 'users/store' => 'users#store'
    post 'users/edit/:id', to: 'users#edit'
    post 'users/delete/:id', to: 'users#delete'
    post 'users/restore/:id', to: 'users#restore'
    #PROYECTOS ROUTES
    get 'proyectos/index'
    get 'proyectos/create' => 'proyectos#create'
    get 'proyectos/search'
    get 'proyectos/show_ended'
    get 'proyectos/update' => 'proyectos#update'
    post 'proyectos/store' => 'proyectos#store'
    post 'proyectos/edit/:id', to: 'proyectos#edit'
    post 'proyectos/edit_lider/:id', to: 'proyectos#edit_lider'
    post 'proyectos/delete/:id', to: 'proyectos#delete'
    #DASHBOARD ROUTES
    get 'dashboard/index'
    get 'dashboard/change'
    post 'dashboard/change-password/:id' => 'dashboard#changePass'
    #ERROR ROUTES
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"

    #RUTAS PARA METODOLOGÍA TSP
    namespace :lanzamiento do
      #LANZAMIENTO::PERSONAL
      get 'personal/index'
      get 'personal/add' => 'personal#add'
      post 'personal/store' => 'personal#store'
      post 'personal/delete/:id', to: 'personal#delete'
      #LANZAMIENTO::METAS
      get 'metas/index'
      get 'metas/create' => 'metas#create'
      get 'metas/update' => 'metas#update'
      post 'metas/store' => 'metas#store'
      post 'metas/edit/:id', to: 'metas#edit'
      post 'metas/delete/:id', to: 'metas#delete'
    end
    namespace :planeacion do
      #PLANEACION::PLANES_DE_CALIDAD
      get 'planes_calidad/index'
      get 'planes_calidad/create' => 'planes_calidad#create'
      get 'planes_calidad/update' => 'planes_calidad#update'
      post 'planes_calidad/store' => 'planes_calidad#store'
      post 'planes_calidad/edit/:id', to: 'planes_calidad#edit'
      post 'planes_calidad/delete/:id', to: 'planes_calidad#delete'
    end
    namespace :estrategia do
      #ESTRATEGIA::CRITERIOS
      get 'criterios/index'
      get 'criterios/create' => 'criterios#create'
      get 'criterios/update' => 'criterios#update'
      post 'criterios/store' => 'criterios#store'
      post 'criterios/edit/:id', to: 'criterios#edit'
      post 'criterios/delete/:id', to: 'criterios#delete'
      #ESTRATEGIA::DISEÑOS
      get 'disenos/index'
      get 'disenos/create' => 'disenos#create'
      get 'disenos/update' => 'disenos#update'
      post 'disenos/store' => 'disenos#store'
      post 'disenos/edit/:id', to: 'disenos#edit'
      post 'disenos/delete/:id', to: 'disenos#delete'
      #ESTRATEGIA::ESTIMACIONES
      get 'estimaciones/index'
      get 'estimaciones/create'
      get 'estimaciones/update'
      post 'estimaciones/store' => 'estimaciones#store'
      post 'estimaciones/edit/:id', to: 'estimaciones#edit'
      post 'estimaciones/delete/:id', to: 'estimaciones#delete'
    end
    namespace :requerimientos do
      #REQUERIMIENTOS::REQUERIMIENTOS
      get 'requerimientos/index'
      get 'requerimientos/create' => 'requerimientos#create'
      get 'requerimientos/update' => 'requerimientos#update'
      post 'requerimientos/store' => 'requerimientos#store'
      post 'requerimientos/edit/:id', to: 'requerimientos#edit'
      post 'requerimientos/delete/:id', to: 'requerimientos#delete'
    end
    namespace :postmortem do
      #POSTMORTEM::RESUMENES
      get 'resumenes/index'
      get 'resumenes/create' => 'resumenes#create'
      get 'resumenes/update' => 'resumenes#update'
      post 'resumenes/store' => 'resumenes#store'
      post 'resumenes/edit/:id', to: 'resumenes#edit'
      post 'resumenes/update_project/:proyecto_id', to: 'resumenes#update_ciclo_proyecto'
      post 'resumenes/end_project/:proyecto_id', to: 'resumenes#end_proyecto'
      post 'resumenes/delete/:id', to: 'resumenes#delete'
    end
    namespace :pruebas do
      #PRUEBAS::PRUEBAS
      get 'pruebas/index'
      get 'pruebas/create'
      get 'pruebas/update'
      post 'pruebas/store' => 'pruebas#store'
      post 'pruebas/edit/:id', to: 'pruebas#edit'
      post 'pruebas/delete/:id', to: 'pruebas#delete'
    end
    namespace :implementacion do
      get 'criterios_calidad/index'
      get 'criterios_calidad/create'
      get 'criterios_calidad/update'
      post 'criterios_calidad/store' => 'criterios_calidad#store'
      post 'criterios_calidad/edit/:id', to: 'criterios_calidad#edit'
      post 'criterios_calidad/delete/:id', to: 'criterios_calidad#delete'
    end
    namespace :diseno do
      #DISENO::TIPOS_ESTANDARES
      get 'tipos_estandares/index'
      get 'tipos_estandares/create'
      get 'tipos_estandares/update'
      post 'tipos_estandares/store' => 'tipos_estandares#store'
      post 'tipos_estandares/edit/:id', to: 'tipos_estandares#edit'
      post 'tipos_estandares/delete/:id', to: 'tipos_estandares#delete'
      #DISENO::ESTANDARES
      get 'estandares/index'
      get 'estandares/create'
      get 'estandares/update'
      post 'estandares/store' => 'estandares#store'
      post 'estandares/edit/:id', to: 'estandares#edit'
      post 'estandares/delete/:id', to: 'estandares#delete'
      #DISENO::PLANES_PRUEBAS
      get 'planes_pruebas/index'
      get 'planes_pruebas/create'
      get 'planes_pruebas/update'
      post 'planes_pruebas/store' => 'planes_pruebas#store'
      post 'planes_pruebas/edit/:id', to: 'planes_pruebas#edit'
      post 'planes_pruebas/delete/:id', to: 'planes_pruebas#delete'
      #DISENO::ESTRUCUTURAS
      get 'estructuras/index'
      get 'estructuras/create'
      get 'estructuras/update'
      post 'estructuras/store' => 'estructuras#store'
      post 'estructuras/edit/:id', to: 'estructuras#edit'
      post 'estructuras/delete/:id', to: 'estructuras#delete'
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/requerimientos.rb
module Requerimientos
  def self.table_name_prefix
    'requerimientos_'
  end
end

app/models/requerimientos/requerimiento.rb
class Requerimientos::Requerimiento < ApplicationRecord
end

app/controllers/requerimientos/requerimientos_controller.rb
class Requerimientos::RequerimientosController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource

  layout 'application_dashboard'

  def index
    begin
      @proyecto = Proyecto.find(params[:proyecto_id])
      @colaboradors = nil
      if current_user.role_id == 2
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id])
      else
        @colaboradors = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id)
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "No se ha seleccionado el proyecto"
      redirect_to dashboard_index_path
    end
  end

  def create
    @requerimiento = Requerimientos::Requerimiento.new
  end

  def store
    #Definición e inicialización de nueva Requerimientos
    @colaborador = Colaborador.where(proyecto_id: params[:proyecto_id], user_id: current_user.id).first
    @requerimiento = Requerimientos::Requerimiento.new(parametros)
    #obteniendo el ciclo del proyecto
    @requerimiento.ciclo = Proyecto.find(params[:proyecto_id]).ciclo_actual
    @requerimiento.colaborador_id = @colaborador.id
    if(@requerimiento.save)
      #Impresión del proceso satisfactorio
      flash[:success] = "Requerimiento Creado Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "No se pudo crear el Requerimiento"
    end
      redirect_to requerimientos_requerimientos_index_path(:proyecto_id => params[:proyecto_id])
  end

  def edit
    @requerimiento = Requerimientos::Requerimiento.find(params[:id])
    @requerimiento = Requerimientos::Requerimiento.where(id: @requerimiento).first
    if @requerimiento.update(parametros)
      #Impresión del proceso satisfactorio
      flash[:success] = "Requerimiento Actualizado Correctamente"
    else
      #Impresión del proceso de error
      flash[:danger] = "Requerimiento actualiza la estimación"
    end
      redirect_to requerimientos_requerimientos_index_path(:proyecto_id => params[:proyecto_id])
  end

  def update
    begin
      @requerimiento = Requerimientos::Requerimiento.find(params[:id])
      @requerimiento = Requerimientos::Requerimiento.where(id: @requerimiento)
    rescue ActiveRecord::RecordNotFound => e
      @requerimiento = nil
      flash[:danger] = "Requerimiento No Existe"
      redirect_to requerimientos_requerimientos_index_path(:proyecto_id => params[:proyecto_id])
    end
  end

  def delete
    @requerimiento = Requerimientos::Requerimiento.find(params[:id])
    Requerimientos::Requerimiento.where(id: @requerimiento).destroy_all
    flash[:success] = "Requerimiento Eliminado"
    redirect_to requerimientos_requerimientos_index_path(:proyecto_id => params[:proyecto_id])
  end

  private
  def parametros
    params.permit(:descripcion, :fuente, :tipo, :tamano, :ambiente, :restricciones, :procesos, :tiempo, :ciclo)
  end
end

app/helpers/requerimientos/requerimientos_helper.rb
module Requerimientos::RequerimientosHelper
end

app/views/requerimientos/requerimientos/create.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=Proyecto.find(params[:proyecto_id]).nombre%></h2>
    <br>
    <div class="container">
        <div class="row justify-content-md-center align-items-center">
            <div class="col-md-10 align-item-center">
            <div class="card text-center">
                <div class="card-header">
                    <h3>Requerimientos  : :  Requerimientos | Crear Rquerimiento</h3>
                </div>
                <div class="card-body bg-aqua justify-content-center">
                    <form method="POST" action="store" accept-charset="UTF-8" role="form" id="crearrequerimiento" name="crearrequerimiento" enctype="multipart/form-data"> 
                        <!-- Protección CSRF -->
                        <%= token_tag nil %>
                        <div class="row">
                            <div class="col-md-2">
                                <input type="hidden" id="proyecto_id" name="proyecto_id" value="<%=params[:proyecto_id]%>">
                                <label class="text-white">Descripción</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Descripción" id="descripcion" name="descripcion" required></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Fuente</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="text" class="form-control" placeholder="Fuente" id="fuente" name="fuente" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Tipo</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <select type="select" class="form-control" name="tipo" id="tipo">
                                    <option value="" selected>Seleccione un Tipo</option>
                                    <option value="Funcional">Funcional</option>
                                    <option value="No Funcional">No Funcional</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Ambiente</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="text" class="form-control" placeholder="Ambiente" id="ambiente" name="ambiente" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Restricciones</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Restricciones" id="restricciones" name="restricciones" required></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Procesos</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="text" class="form-control" placeholder="Procesos" id="procesos" name="procesos" required>
                            </div>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <button type="submit" class="btn btn-light">Guardar</button>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <%= link_to 'Cancelar', url_for(:back), class: "btn btn-warning" %>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>

app/views/requerimientos/requerimientos/index.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=@proyecto.nombre%></h2>
    <br>
    <div class="card bg-aqua">
        <div class="row card-header text-white">
            <h3 class="col-md-10">Requerimientos  : :  Requerimientos</h3>
            <%= link_to 'Agregar Requerimiento', requerimientos_requerimientos_create_path(:proyecto_id => @proyecto.id), class: "btn btn-light col-md-2 float-right" %>
        </div>
        <table class="table table-hover table-sm table-dark card-body">
            <thead>
                <tr>
                <th scope="col">Descripción</th>
                <th scope="col">Fuente</th>
                <th scope="col">Tipo</th>
                <th scope="col">Ambiente</th>
                <th scope="col">Restricciones</th>
                <th scope="col">Procesos</th>
                <th scope="col" style="width: 10%">Acciones</th>
                </tr>
            </thead>
            <tbody>
            <% @colaboradors.each do |colab|%>
                <% colab.requerimientos_requerimientos.each do |req|%>
                    <tr>
                    <td><%=req.descripcion%></td>
                    <td><%=req.fuente%></td>
                    <td><%=req.tipo%></td>
                    <td><%=req.ambiente%></td>
                    <td><%=req.restricciones%></td>
                    <td><%=req.procesos%></td>
                    <td>
                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-6 px-0">
                                <div class="d-inline-flex">
                                    <a href="/requerimientos/requerimientos/update?id=<%= req.id %>&proyecto_id=<%=@proyecto.id%>" title="Editar">
                                        <%= image_tag("edit.png", :alt=>"Editar", :width => '30%', :style => " filter: invert(100%)" )%>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6 px-0">
                                <form method="POST" action="/requerimientos/requerimientos/delete/<%=req.id%>&proyecto_id=<%=@proyecto.id%>" accept-charset="UTF-8" class="form-horizontal" role="form">
                                <!-- Protección CSRF -->
                                <%= token_tag nil %>
                                <div class="d-inline-flex">
                                    <input type="submit" class="btn-delete" title="Eliminar" data-confirm="¿Desea eliminar el requerimiento <%=req.descripcion%>?" data-title="Eliminar Requerimiento" data-commit="Eliminar" data-cancel="Cancelar">
                                </div>
                                </form>
                            </div>
                        </div>
                    </td>
                    </tr>
                <% end %>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/requerimientos/requerimientos/update.html.erb
<div class="container">
    <h2 class="h2 text-white text-center"><%=Proyecto.find(params[:proyecto_id]).nombre%></h2>
    <br>
    <div class="container">
        <div class="row justify-content-md-center align-items-center">
            <div class="col-md-10 align-item-center">
            <div class="card text-center">
                <div class="card-header">
                    <h3>Requerimientos  : :  Requerimientos | Actualizar Rquerimiento</h3>
                </div>
                <div class="card-body bg-aqua justify-content-center">
                <% @requerimiento.each do |requerimiento| %>
                    <form method="POST" action="store" accept-charset="UTF-8" role="form" id="actualizarrequerimiento" name="actualizarrequerimiento" enctype="multipart/form-data"> 
                        <!-- Protección CSRF -->
                        <%= token_tag nil %>
                        <div class="row">
                            <div class="col-md-2">
                                <input type="hidden" id="proyecto_id" name="proyecto_id" value="<%=params[:proyecto_id]%>">
                                <label class="text-white">Descripción</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Descripción" id="descripcion" name="descripcion" required><%=requerimiento.descripcion%></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Fuente</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="text" class="form-control" placeholder="Fuente" id="fuente" name="fuente" required value="<%=requerimiento.fuente%>">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Tipo</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <select type="select" class="form-control" name="tipo" id="tipo">
                                    <option value="" selected>Seleccione un Tipo</option>
                                    <% if requerimiento.tipo == "Funcional" %>
                                        <option value="Funcional" selected>Funcional</option>
                                        <option value="No Funcional">No Funcional</option>
                                    <%else%>
                                        <option value="Funcional">Funcional</option>
                                        <option value="No Funcional" selected>No Funcional</option>
                                    <%end%>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Ambiente</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="text" class="form-control" placeholder="Ambiente" id="ambiente" name="ambiente" required value="<%=requerimiento.admbiente%>">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Restricciones</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <textarea type="text" class="form-control" placeholder="Restricciones" id="restricciones" name="restricciones" required><%=requerimiento.restricciones%></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label class="text-white">Procesos</label>
                            </div>
                            <div class="col-md-10 input-group form-group">
                                <input type="text" class="form-control" placeholder="Procesos" id="procesos" name="procesos" required value="<%=requerimiento.procesos%>">
                            </div>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <button type="submit" class="btn btn-light">Guardar</button>
                        </div>
                        <div class="form-group d-inline-flex mt-3">
                            <%= link_to 'Cancelar', url_for(:back), class: "btn btn-warning" %>
                        </div>
                    </form>
                    </div>
                    <%end%>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>